# Generated by Django 3.2.11 on 2022-03-19 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_product_list_policy_followed'),
        ('core', '0002_prizelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prizelist',
            name='product_as_prize',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.product_list'),
        ),
    ]
