# Generated by Django 3.2.11 on 2022-03-19 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_prizelist_product_as_prize'),
    ]

    operations = [
        migrations.AddField(
            model_name='prizelist',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
