# Generated by Django 3.2.11 on 2022-04-06 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pointwallet_spent_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointwallet',
            name='available',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='pointwallet',
            name='purchased',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='pointwallet',
            name='spent',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='pointwallet',
            name='spent_amount',
            field=models.CharField(blank=True, default='0', max_length=255, null=True),
        ),
    ]
