# Generated by Django 3.2.11 on 2022-04-09 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0060_alter_woocommerceproductlist_product_img'),
        ('core', '0006_auto_20220407_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prizelist',
            name='product_as_prize',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.productlist'),
        ),
    ]
