# Generated by Django 3.2.11 on 2022-04-30 23:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_alter_prizelist_product_as_prize'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.CharField(default='0', max_length=255)),
                ('purchased', models.CharField(default='0', max_length=255)),
                ('spent', models.CharField(default='0', max_length=255)),
                ('spent_amount', models.CharField(blank=True, default='0', max_length=255, null=True)),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
