# Generated by Django 3.2.11 on 2022-05-06 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_creditpurchasinghistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditpurchasinghistory',
            old_name='payer_address',
            new_name='payer_post_code',
        ),
        migrations.AddField(
            model_name='creditpurchasinghistory',
            name='payer_country_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
