# Generated by Django 3.2.11 on 2022-05-11 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_winningchancepurchasinghistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='prizelist',
            name='prize_type',
            field=models.CharField(choices=[('point', 'Point'), ('product', 'Product')], default='', max_length=10),
        ),
    ]
