# Generated by Django 3.2.11 on 2022-05-11 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_prizelist_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='prizelist',
            name='delivery_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
