# Generated by Django 3.2.11 on 2022-05-13 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_prizelist_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='winningchance',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='winningchance',
            name='purchased',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='winningchance',
            name='spent',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
