# Generated by Django 3.2.11 on 2022-05-21 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20220513_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='prizelist',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
