# Generated by Django 3.2.11 on 2022-05-31 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0021_auto_20220601_0030'),
        ('product', '0084_alter_offeredproductitemsbymembershiprank_product'),
        ('core', '0019_referalbonuslist'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0.0)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminPanel.packagenamelist')),
                ('options', models.ManyToManyField(to='adminPanel.PackageOptions')),
                ('products', models.ManyToManyField(to='product.ProductList')),
            ],
        ),
    ]
