# Generated by Django 3.2.11 on 2022-05-31 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_packagelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagelist',
            name='package_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
