# Generated by Django 3.2.11 on 2022-05-31 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_packagelist_package_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagelist',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
