# Generated by Django 3.2.11 on 2022-06-01 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_packagelist_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagelist',
            name='old_price',
            field=models.FloatField(default=0.0),
        ),
    ]
