# Generated by Django 3.2.11 on 2022-06-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20220606_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailinvitationbonususerlist',
            name='mail_to',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
