# Generated by Django 3.2.11 on 2022-06-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_bonuspoinforregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winningchance',
            name='spent',
            field=models.CharField(blank=True, default='0', max_length=255, null=True),
        ),
    ]
