# Generated by Django 3.2.11 on 2022-06-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_winningchance_spent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winningchance',
            name='purchased',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
