# Generated by Django 3.2.11 on 2022-06-13 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_pointtocreditconversionhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winningchance',
            name='purchased',
            field=models.CharField(blank=True, default='0', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='winningchance',
            name='remaining_chances',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
