# Generated by Django 3.2.11 on 2022-06-15 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20220614_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointwallet',
            name='total_pointsOf_crnt_user',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
