# Generated by Django 3.2.11 on 2022-06-15 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_pointwallet_total_pointsof_crnt_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointwallet',
            name='available',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pointwallet',
            name='purchased',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
