# Generated by Django 3.2.11 on 2022-06-15 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20220615_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditwallet',
            name='available',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='creditwallet',
            name='purchased',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='creditwallet',
            name='spent',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='creditwallet',
            name='spent_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
