# Generated by Django 3.2.11 on 2022-06-15 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20220615_1108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditwallet',
            old_name='spent_amount',
            new_name='total_credts_ofCurrentUser',
        ),
    ]
