# Generated by Django 3.2.11 on 2022-06-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20220615_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditpurchasinghistory',
            name='paid_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
