# Generated by Django 3.2.11 on 2022-06-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_creditpurchasinghistory_paid_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winningchancepurchasinghistory',
            name='point_charged',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
