# Generated by Django 3.2.11 on 2022-06-16 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_winningchancepurchasinghistory_point_charged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winningchancepurchasinghistory',
            name='amount_paid',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='winningchancepurchasinghistory',
            name='point_charged',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
