# Generated by Django 3.2.11 on 2022-03-02 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminPanel', '0004_contactus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('brand_name', models.CharField(blank=True, max_length=255, null=True)),
                ('old_price', models.FloatField()),
                ('new_price', models.FloatField()),
                ('short_des', models.TextField()),
                ('details', models.TextField()),
                ('product_thumbnail', models.ImageField(upload_to='product_thumbnail_img')),
                ('use_case', models.TextField(blank=True, null=True)),
                ('benefits', models.TextField(blank=True, null=True)),
                ('security_policy', models.TextField(blank=True, null=True)),
                ('return_policy', models.TextField(blank=True, null=True)),
                ('delivery_policy', models.TextField(blank=True, null=True)),
                ('store_name', models.CharField(blank=True, max_length=255, null=True)),
                ('store_link', models.CharField(blank=True, max_length=255, null=True)),
                ('about_store', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='adminPanel.productcategory')),
                ('subcategory', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='adminPanel.productsubcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='product_img')),
                ('img1', models.ImageField(upload_to='product_img')),
                ('img2', models.ImageField(upload_to='product_img')),
                ('img3', models.ImageField(upload_to='product_img')),
                ('img4', models.ImageField(upload_to='product_img')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.product_list')),
            ],
        ),
    ]
