# Generated by Django 3.2.11 on 2022-03-03 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_image',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='product_img'),
        ),
        migrations.AlterField(
            model_name='product_image',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='product_img'),
        ),
        migrations.AlterField(
            model_name='product_image',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='product_img'),
        ),
        migrations.AlterField(
            model_name='product_image',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='product_img'),
        ),
        migrations.AlterField(
            model_name='product_image',
            name='img4',
            field=models.ImageField(blank=True, null=True, upload_to='product_img'),
        ),
    ]
