# Generated by Django 3.2.11 on 2022-03-03 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20220303_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_list',
            name='product_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
