# Generated by Django 3.2.11 on 2022-03-03 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_list_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_list',
            name='about_store',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='product_list',
            name='benefits',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='product_list',
            name='delivery_policy',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='product_list',
            name='return_policy',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='product_list',
            name='security_policy',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='product_list',
            name='use_case',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
