# Generated by Django 3.2.11 on 2022-03-03 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0004_contactus'),
        ('product', '0004_auto_20220303_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_list',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminPanel.productcategory'),
        ),
        migrations.AlterField(
            model_name='product_list',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminPanel.productsubcategory'),
        ),
    ]
