# Generated by Django 3.2.11 on 2022-03-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_productrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_list',
            name='total_sold',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
