# Generated by Django 3.2.11 on 2022-03-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_list_total_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_list',
            name='in_stock',
            field=models.CharField(blank=True, default='0', max_length=255, null=True),
        ),
    ]
