# Generated by Django 3.2.11 on 2022-03-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_list_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_list',
            name='policy_followed',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
