# Generated by Django 3.2.11 on 2022-03-22 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20220322_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='woocommerceprodctimages',
            name='img1_url1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='woocommerceprodctimages',
            name='img1_url2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='woocommerceprodctimages',
            name='img1_url3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='woocommerceprodctimages',
            name='img1_url4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='woocommerceprodctimages',
            name='img1_url5',
            field=models.TextField(blank=True, null=True),
        ),
    ]
