# Generated by Django 3.2.11 on 2022-03-22 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20220322_1225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='woocommerceproductlist',
            options={'ordering': ['-pk']},
        ),
    ]
