# Generated by Django 3.2.11 on 2022-03-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_woocommerceproductlist_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_list',
            name='sponsr_as_prize',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='woocommerceproductlist',
            name='sponsr_as_prize',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
