# Generated by Django 3.2.11 on 2022-03-25 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_product_list_sponsor_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_list',
            options={'ordering': ['pk']},
        ),
    ]
