# Generated by Django 3.2.11 on 2022-03-25 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_product_list_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_list',
            options={'ordering': ['-pk']},
        ),
    ]
