# Generated by Django 3.2.11 on 2022-03-26 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0018_alter_product_list_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_amount_or_title', models.CharField(blank=True, max_length=255, null=True)),
                ('offer_duration', models.CharField(blank=True, max_length=255, null=True)),
                ('product_title', models.CharField(blank=True, max_length=255, null=True)),
                ('starting_price', models.CharField(blank=True, max_length=255, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='banner')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
