# Generated by Django 3.2.11 on 2022-03-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_bannerlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerlist',
            name='product_url',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
