# Generated by Django 3.2.11 on 2022-03-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_bannerlist_product_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerlist',
            name='banner_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
