# Generated by Django 3.2.11 on 2022-03-28 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_auto_20220327_0141'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllProductList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(blank=True, choices=[('wsp', 'Woocommerce store product'), ('mcp', 'Custom Product')], max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('custom_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.product_list')),
                ('woocmrce_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.woocommerceproductlist')),
            ],
        ),
    ]
