# Generated by Django 3.2.11 on 2022-03-31 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_alter_product_list_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_list',
            name='avrg_rating',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product_list',
            name='rating_count',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product_list',
            name='slug',
            field=models.TextField(blank=True, null=True),
        ),
    ]
