# Generated by Django 3.2.11 on 2022-03-31 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_auto_20220401_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_list',
            name='brand_name',
            field=models.CharField(blank=True, default='brand_name', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product_list',
            name='details',
            field=models.TextField(blank=True, default='Details', null=True),
        ),
        migrations.AlterField(
            model_name='product_list',
            name='new_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product_list',
            name='old_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product_list',
            name='short_des',
            field=models.TextField(blank=True, default='Description', null=True),
        ),
    ]
