# Generated by Django 3.2.11 on 2022-03-31 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_auto_20220401_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_list',
            name='avrg_rating',
            field=models.CharField(blank=True, default='0', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product_list',
            name='benefits',
            field=models.TextField(blank=True, default='Not added', null=True),
        ),
        migrations.AlterField(
            model_name='product_list',
            name='cat_id',
            field=models.CharField(blank=True, default='id', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product_list',
            name='cat_name',
            field=models.CharField(blank=True, default='cat_name', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product_list',
            name='delivery_policy',
            field=models.TextField(blank=True, default='Not added', null=True),
        ),
        migrations.AlterField(
            model_name='product_list',
            name='policy_followed',
            field=models.CharField(blank=True, default='Not selected', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product_list',
            name='product_id',
            field=models.CharField(blank=True, default='id', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product_list',
            name='rating_count',
            field=models.CharField(blank=True, default='0', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product_list',
            name='return_policy',
            field=models.TextField(blank=True, default='Not added', null=True),
        ),
        migrations.AlterField(
            model_name='product_list',
            name='security_policy',
            field=models.TextField(blank=True, default='Not added', null=True),
        ),
        migrations.AlterField(
            model_name='product_list',
            name='slug',
            field=models.TextField(blank=True, default='slug', null=True),
        ),
        migrations.AlterField(
            model_name='product_list',
            name='sponsor_status',
            field=models.CharField(blank=True, default='No', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product_list',
            name='store_link',
            field=models.CharField(blank=True, default='Not added', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product_list',
            name='store_name',
            field=models.CharField(blank=True, default='Not added', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product_list',
            name='subcat_id',
            field=models.CharField(blank=True, default='id', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product_list',
            name='subcat_name',
            field=models.CharField(blank=True, default='subcat_name', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product_list',
            name='use_case',
            field=models.TextField(blank=True, default='Not added', null=True),
        ),
        migrations.AlterField(
            model_name='product_list',
            name='woocmrce_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.woocommerceproductlist'),
        ),
    ]
