# Generated by Django 3.2.11 on 2022-04-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_cart_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='quantity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
