# Generated by Django 3.2.11 on 2022-04-02 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0038_auto_20220401_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
