# Generated by Django 3.2.11 on 2022-04-02 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0040_orderlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlist',
            name='items',
            field=models.ManyToManyField(blank=True, to='product.Cart'),
        ),
    ]
