# Generated by Django 3.2.11 on 2022-04-03 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0044_alter_orderlist_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditem',
            name='order_status',
            field=models.CharField(blank=True, choices=[('curnt', 'Current Order'), ('prev', 'Previous Order')], max_length=255, null=True),
        ),
    ]
