# Generated by Django 3.2.11 on 2022-04-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0046_auto_20220403_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlist',
            name='order_status',
            field=models.CharField(blank=True, choices=[('a', 'Approved'), ('p', 'Pending'), ('c', 'Cancel')], max_length=255, null=True),
        ),
    ]
