# Generated by Django 3.2.11 on 2022-04-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0047_alter_orderlist_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='payment_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
