# Generated by Django 3.2.11 on 2022-04-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0048_orderlist_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
