# Generated by Django 3.2.11 on 2022-04-06 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0049_orderlist_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_list',
            name='woocmrce_product_img',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.woocommerceprodctimages'),
        ),
    ]
