# Generated by Django 3.2.11 on 2022-04-06 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0051_alter_product_list_woocmrce_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_list',
            name='woocmrce_product_img',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.woocommerceprodctimages'),
        ),
    ]
