# Generated by Django 3.2.11 on 2022-04-06 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0052_alter_product_list_woocmrce_product_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_list',
            name='woocmrce_product_img',
        ),
    ]
