# Generated by Django 3.2.11 on 2022-04-07 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0053_remove_product_list_woocmrce_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='total_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
