# Generated by Django 3.2.11 on 2022-04-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0054_orderlist_total_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(blank=True, max_length=255, null=True)),
                ('product_type', models.CharField(blank=True, max_length=5, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='productImg')),
                ('img_link', models.CharField(blank=True, max_length=500, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='product_list',
            name='productImg',
            field=models.ManyToManyField(blank=True, null=True, to='product.ProductImg'),
        ),
    ]
