# Generated by Django 3.2.11 on 2022-04-08 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0006_sitelogo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0055_auto_20220408_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(blank=True, choices=[('wsp', 'Woocommerce store product'), ('mcp', 'Custom Product')], max_length=255, null=True)),
                ('product_id', models.CharField(blank=True, default='id', max_length=255, null=True)),
                ('slug', models.TextField(blank=True, default='slug', null=True)),
                ('cat_id', models.CharField(blank=True, default='id', max_length=255, null=True)),
                ('cat_name', models.CharField(blank=True, default='cat_name', max_length=255, null=True)),
                ('subcat_id', models.CharField(blank=True, default='id', max_length=255, null=True)),
                ('subcat_name', models.CharField(blank=True, default='subcat_name', max_length=255, null=True)),
                ('title', models.TextField(blank=True, default='title', null=True)),
                ('brand_name', models.CharField(blank=True, default='brand_name', max_length=255, null=True)),
                ('old_price', models.FloatField(blank=True, default=0, null=True)),
                ('new_price', models.FloatField(blank=True, default=0, null=True)),
                ('short_des', models.TextField(blank=True, default='Description', null=True)),
                ('details', models.TextField(blank=True, default='Details', null=True)),
                ('product_thumbnail', models.ImageField(blank=True, null=True, upload_to='product_thumbnail_img')),
                ('policy_followed', models.CharField(blank=True, default='Not selected', max_length=255, null=True)),
                ('use_case', models.TextField(blank=True, default='Not added', null=True)),
                ('benefits', models.TextField(blank=True, default='Not added', null=True)),
                ('security_policy', models.TextField(blank=True, default='Not added', null=True)),
                ('return_policy', models.TextField(blank=True, default='Not added', null=True)),
                ('delivery_policy', models.TextField(blank=True, default='Not added', null=True)),
                ('store_name', models.CharField(blank=True, default='Not added', max_length=255, null=True)),
                ('store_link', models.CharField(blank=True, default='Not added', max_length=255, null=True)),
                ('about_store', models.TextField(blank=True, default='', null=True)),
                ('total_sold', models.IntegerField(blank=True, default=0, null=True)),
                ('in_stock', models.CharField(blank=True, default='0', max_length=255, null=True)),
                ('avrg_rating', models.CharField(blank=True, default='0', max_length=255, null=True)),
                ('rating_count', models.CharField(blank=True, default='0', max_length=255, null=True)),
                ('price', models.CharField(blank=True, max_length=255, null=True)),
                ('regular_price', models.CharField(blank=True, max_length=255, null=True)),
                ('sponsr_as_prize', models.BooleanField(blank=True, default=False, null=True)),
                ('sponsor_status', models.CharField(blank=True, default='No', max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminPanel.productcategory')),
                ('productImg', models.ManyToManyField(blank=True, null=True, to='product.ProductImg')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminPanel.productsubcategory')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
