# Generated by Django 3.2.11 on 2022-04-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0056_productlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlist',
            name='productImg',
            field=models.ManyToManyField(blank=True, to='product.ProductImg'),
        ),
    ]
