# Generated by Django 3.2.11 on 2022-04-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0057_alter_productlist_productimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_list',
            name='productImg',
            field=models.ManyToManyField(blank=True, to='product.ProductImg'),
        ),
    ]
