# Generated by Django 3.2.11 on 2022-04-14 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0064_productrating_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlist',
            name='refund_policy',
            field=models.TextField(blank=True, default='Not added', null=True),
        ),
    ]
