# Generated by Django 3.2.11 on 2022-04-14 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0065_productlist_refund_policy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_list',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product_list',
            name='productImg',
        ),
        migrations.RemoveField(
            model_name='product_list',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='product_list',
            name='user',
        ),
        migrations.RemoveField(
            model_name='product_list',
            name='woocmrce_product',
        ),
        migrations.DeleteModel(
            name='Product_image',
        ),
        migrations.DeleteModel(
            name='Product_list',
        ),
    ]
