# Generated by Django 3.2.11 on 2022-04-14 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0066_auto_20220414_0831'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WoocommerceProdctImages',
        ),
    ]
