# Generated by Django 3.2.11 on 2022-04-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0068_bannerlist_offer_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='payment_options',
            field=models.CharField(blank=True, choices=[('cod', 'Cash on Delivery')], max_length=35, null=True),
        ),
    ]
