# Generated by Django 3.2.11 on 2022-04-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0069_orderlist_payment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='shipping_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
