# Generated by Django 3.2.11 on 2022-04-17 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0070_orderlist_shipping_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
