# Generated by Django 3.2.11 on 2022-05-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0072_homeminibottombanner_homeminitopbanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeminibottombanner',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='homeminitopbanner',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
