# Generated by Django 3.2.11 on 2022-05-16 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0075_couponcode_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedCouponHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_got', models.CharField(blank=True, max_length=24, null=True)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.couponcode')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.orderlist')),
            ],
        ),
    ]
