# Generated by Django 3.2.11 on 2022-05-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0076_appliedcouponhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='sub_total_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
