# Generated by Django 3.2.11 on 2022-05-19 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0077_orderlist_sub_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponcode',
            name='coupon_banner',
            field=models.ImageField(blank=True, null=True, upload_to='coupon_banner'),
        ),
        migrations.AddField(
            model_name='couponcode',
            name='terms_conditions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
