# Generated by Django 3.2.11 on 2022-05-20 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0079_auto_20220520_2253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='woocommerceproductlist',
            options={'ordering': ['-pk']},
        ),
    ]
