# Generated by Django 3.2.11 on 2022-05-20 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0080_alter_woocommerceproductlist_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='woocommerceproductlist',
            options={'ordering': ['pk']},
        ),
    ]
