# Generated by Django 3.2.11 on 2022-05-28 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0016_membershiprank_rank_id'),
        ('product', '0081_alter_woocommerceproductlist_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferedSingleProductBasedOnMembershipRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.IntegerField(blank=True, default=0)),
                ('offered_price', models.FloatField(blank=True, default=0.0)),
                ('membership_rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminPanel.membershiprank')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productlist')),
                ('product_cat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='adminPanel.productcategory')),
            ],
        ),
    ]
