# Generated by Django 3.2.11 on 2022-05-29 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0083_offeredproductitemsbymembershiprank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offeredproductitemsbymembershiprank',
            name='product',
            field=models.ManyToManyField(blank=True, to='product.ProductList'),
        ),
    ]
