# Generated by Django 3.2.11 on 2022-06-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0084_alter_offeredproductitemsbymembershiprank_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlist',
            name='product_height',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productlist',
            name='product_length',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productlist',
            name='product_weight',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productlist',
            name='product_width',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='woocommerceproductlist',
            name='product_height',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='woocommerceproductlist',
            name='product_length',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='woocommerceproductlist',
            name='product_weight',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='woocommerceproductlist',
            name='product_width',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
