# Generated by Django 3.2.11 on 2022-06-09 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0085_auto_20220609_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('cost_rate', models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='productlist',
            name='shipping_class',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.shippingclass'),
        ),
    ]
