# Generated by Django 3.2.11 on 2022-06-09 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0086_auto_20220610_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingclass',
            name='classID',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
