# Generated by Django 3.2.11 on 2022-06-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0087_shippingclass_classid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductWeightCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria_id', models.CharField(blank=True, max_length=255, null=True)),
                ('min_weight', models.FloatField(default=0)),
                ('max_weight', models.FloatField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
