# Generated by Django 3.2.11 on 2022-06-10 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0088_productweightcriteria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlist',
            name='product_weight',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
