# Generated by Django 3.2.11 on 2022-06-10 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0089_alter_productlist_product_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlist',
            name='product_weight',
            field=models.FloatField(blank=True, default=0, max_length=255, null=True),
        ),
    ]
