# Generated by Django 3.2.11 on 2022-06-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0092_auto_20220610_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlist',
            name='product_height',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='productlist',
            name='product_length',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='productlist',
            name='product_weight',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='productlist',
            name='product_width',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
