# Generated by Django 3.2.11 on 2022-06-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0093_auto_20220610_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlist',
            name='product_height',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productlist',
            name='product_length',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productlist',
            name='product_width',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
