# Generated by Django 3.2.11 on 2022-06-10 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0094_auto_20220610_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlist',
            name='shipping_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.shippingclass'),
        ),
    ]
