# Generated by Django 3.2.11 on 2022-06-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0095_alter_productlist_shipping_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='total_shipping_cost',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
