# Generated by Django 3.2.11 on 2022-06-12 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0096_orderlist_total_shipping_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditem',
            name='shipping_cost',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
