# Generated by Django 3.2.11 on 2022-06-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0097_ordereditem_shipping_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlist',
            name='total_shipping_cost',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
