# Generated by Django 3.2.11 on 2022-06-12 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0099_alter_orderlist_total_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPurchasePaymntHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_amount', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payee_email', models.CharField(blank=True, max_length=255, null=True)),
                ('payee_marchnt_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payee_address', models.CharField(blank=True, max_length=255, null=True)),
                ('payer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('payer_email', models.CharField(blank=True, max_length=255, null=True)),
                ('payer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payer_post_code', models.CharField(blank=True, max_length=255, null=True)),
                ('payer_country_code', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.orderlist')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
