# Generated by Django 3.2.11 on 2022-06-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0100_productpurchasepaymnthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlist',
            name='order_status',
            field=models.CharField(blank=True, choices=[('a', 'Approved'), ('p', 'Pending'), ('c', 'Cancelled')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productpurchasepaymnthistory',
            name='paid_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
