# Generated by Django 3.2.11 on 2022-06-16 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0101_auto_20220616_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpurchasepaymnthistory',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.orderlist'),
        ),
    ]
