# Generated by Django 3.2.11 on 2022-06-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0102_alter_productpurchasepaymnthistory_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpurchasepaymnthistory',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
