# Generated by Django 3.2.11 on 2022-06-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0103_productpurchasepaymnthistory_paid_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpurchasepaymnthistory',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
