# Generated by Django 3.2.11 on 2022-06-16 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0104_alter_productpurchasepaymnthistory_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpurchasepaymnthistory',
            name='paid_at',
        ),
    ]
