# Generated by Django 3.2.11 on 2022-03-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0003_aboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_qoute', models.TextField()),
                ('address_line_one', models.CharField(default='', max_length=255)),
                ('address_line_two', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('mobile', models.CharField(default='', max_length=50)),
                ('hotline', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('email_one', models.CharField(default='', max_length=50)),
                ('email_two', models.CharField(blank=True, default='', max_length=50, null=True)),
            ],
        ),
    ]
