# Generated by Django 3.2.11 on 2022-03-31 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0005_cookiepolicy_deliverypolicy_privacypolicy_refundpolicy_returnpolicy_securitypolicy_termsconditions'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logo')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
