# Generated by Django 3.2.11 on 2022-04-21 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0006_sitelogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
