# Generated by Django 3.2.11 on 2022-05-26 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0011_totalnumvisitor_visitorinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorinfo',
            name='country_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visitorinfo',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visitorinfo',
            name='longitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visitorinfo',
            name='timezone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visitorinfo',
            name='visited',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='visitorinfo',
            name='visitors_country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
