# Generated by Django 3.2.11 on 2022-05-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0012_auto_20220527_0112'),
    ]

    operations = [
        migrations.CreateModel(
            name='HowSpinIt2WinWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
