# Generated by Django 3.2.11 on 2022-05-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0013_howspinit2winworks'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberShipRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
