# Generated by Django 3.2.11 on 2022-05-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0015_auto_20220529_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiprank',
            name='rank_id',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
