# Generated by Django 3.2.11 on 2022-05-30 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0018_rename_usermembershipstatus_sellermembershipstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetaTestTermsConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='visitorinfo',
            name='postal_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
