# Generated by Django 3.2.11 on 2022-05-31 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0019_auto_20220531_0127'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageNameList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=20, null=True)),
            ],
        ),
    ]
