# Generated by Django 3.2.11 on 2022-05-31 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0020_packagenamelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(default='', max_length=40)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='packagenamelist',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
