# Generated by Django 3.2.11 on 2022-06-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0021_auto_20220601_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageoptions',
            name='option',
            field=models.CharField(default='', max_length=250),
        ),
    ]
