# Generated by Django 3.2.11 on 2023-03-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0023_memberspolicy_shopperpolicy'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpinConversionRateIntoUSD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('spinRateValueInUSD', models.FloatField(default=0.1)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
