# Generated by Django 3.2.11 on 2022-07-12 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdsColPerRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col_id', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('col_name', models.CharField(default='', max_length=255)),
                ('ads_script', models.TextField(blank=True, default='', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdsPageName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('name', models.CharField(default='', max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdsRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_id', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('name', models.CharField(default='', max_length=255)),
                ('allowed_ads_type', models.CharField(choices=[('hrba', 'Horizontal Rectangle Banner Ads'), ('vrba', 'Vertical Rectangle Banner Ads'), ('sqba', 'Square Banner Ads')], default='', max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('page_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisement.adspagename')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileAds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ads_type', models.CharField(choices=[('banner', 'Banner'), ('product', 'Product')], max_length=25)),
                ('banner_img', models.ImageField(blank=True, null=True, upload_to='user_profile_ads_bnnr')),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('added', models.DateTimeField(auto_now_add=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productlist')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShopPageBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_id', models.CharField(blank=True, max_length=255, null=True)),
                ('img', models.ImageField(upload_to='shopPageBanner')),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.BooleanField(blank=True, default=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BannerProdDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_id', models.CharField(blank=True, max_length=255, null=True)),
                ('img', models.ImageField(upload_to='Product_details_pg_bnr')),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.BooleanField(blank=True, default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdsScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adsScript', models.TextField(default='')),
                ('col', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisement.adscolperrow')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisement.adspagename')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisement.adsrow')),
            ],
        ),
        migrations.AddField(
            model_name='adscolperrow',
            name='row',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisement.adsrow'),
        ),
    ]
