# Generated by Django 3.2.11 on 2022-04-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerproddetail',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
