# Generated by Django 3.2.11 on 2022-04-16 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_bannerproddetail_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerproddetail',
            name='status',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
