# Generated by Django 3.2.11 on 2022-04-20 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advertisement', '0003_bannerproddetail_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopPageBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_id', models.CharField(blank=True, max_length=255, null=True)),
                ('img', models.ImageField(upload_to='shopPageBanner')),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.BooleanField(blank=True, default=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
