# Generated by Django 3.2.11 on 2022-05-14 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0073_auto_20220504_2104'),
        ('advertisement', '0004_shoppagebanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileAds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ads_type', models.CharField(choices=[('banner', 'Banner'), ('product', 'Product')], max_length=25)),
                ('banner_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productlist')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
