# Generated by Django 3.2.11 on 2022-05-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0006_userprofileads_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileads',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
