# Generated by Django 3.2.11 on 2022-06-23 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0008_alter_userprofileads_banner_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdsPageName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdsRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('allowed_ads_type', models.CharField(choices=[('hba', 'Horizontal Banner Ads'), ('vba', 'Vertical Banner Ads'), ('sqba', 'Square Banner Ads')], default='', max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('page_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisement.adspagename')),
            ],
        ),
        migrations.CreateModel(
            name='AdsColPerRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col_name', models.CharField(default='', max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisement.adsrow')),
            ],
        ),
    ]
