# Generated by Django 3.2.11 on 2022-06-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0009_adscolperrow_adspagename_adsrow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adsrow',
            name='allowed_ads_type',
            field=models.CharField(choices=[('hrba', 'Horizontal Rectangle Banner Ads'), ('vrba', 'Vertical Rectangle Banner Ads'), ('sqba', 'Square Banner Ads')], default='', max_length=255),
        ),
    ]
