# Generated by Django 3.2.11 on 2022-06-30 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0010_alter_adsrow_allowed_ads_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='adscolperrow',
            name='ads_script',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
