# Generated by Django 3.2.11 on 2022-06-30 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0011_adscolperrow_ads_script'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdsScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adsScript', models.TextField(default='')),
                ('col', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisement.adscolperrow')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisement.adspagename')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisement.adsrow')),
            ],
        ),
    ]
