# Generated by Django 3.2.11 on 2022-06-30 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0012_adsscript'),
    ]

    operations = [
        migrations.AddField(
            model_name='adspagename',
            name='page_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
