# Generated by Django 3.2.11 on 2022-06-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0013_adspagename_page_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='adscolperrow',
            name='col_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='adsrow',
            name='row_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
