# Generated by Django 3.2.11 on 2022-07-12 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentDelivryRequestPrizeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('is_current', models.BooleanField(blank=True, default=False, null=True)),
                ('shipping_cost', models.FloatField(blank=True, default=0, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_segments', models.CharField(blank=True, max_length=3, null=True)),
                ('no_of_complt_spins', models.CharField(max_length=3)),
                ('spining_duration', models.CharField(max_length=3)),
                ('status', models.BooleanField(blank=True, default=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameTermsPolicies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PointAs_Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_amount', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductPrizeDeliverOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_total_amount', models.FloatField(blank=True, null=True)),
                ('total_amount', models.FloatField(blank=True, null=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('order_status', models.CharField(blank=True, choices=[('a', 'Approved'), ('p', 'Pending'), ('c', 'Cancel')], max_length=255, null=True)),
                ('delivery_status', models.BooleanField(blank=True, default=False, null=True)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('shipping_status', models.BooleanField(blank=True, default=False, null=True)),
                ('shipping_date', models.DateTimeField(blank=True, null=True)),
                ('total_shipping_cost', models.FloatField(blank=True, default=0, null=True)),
                ('order_note', models.TextField(blank=True, null=True)),
                ('payment_status', models.BooleanField(blank=True, default=False, null=True)),
                ('payment_options', models.CharField(blank=True, choices=[('cod', 'Cash on Delivery')], max_length=35, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('billing_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.billinginfo')),
                ('items', models.ManyToManyField(blank=True, to='game.CurrentDelivryRequestPrizeProduct')),
                ('shipping_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.shippinginfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TotalNumOfTimesPlayed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_times_played', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SponsoredProductForPrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodct_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.BooleanField(blank=True, default=False, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productlist')),
            ],
        ),
        migrations.CreateModel(
            name='SegmentList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_no', models.IntegerField(blank=True, default=1, null=True)),
                ('bg_color', models.CharField(max_length=255)),
                ('segment_prize_type', models.CharField(choices=[('1', 'Product'), ('2', 'Point')], max_length=255)),
                ('prize_title', models.CharField(blank=True, max_length=255, null=True)),
                ('product_cost', models.FloatField(blank=True, default=0, null=True)),
                ('prize_point_amount', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.BooleanField(blank=True, default=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('point_as_prize', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.pointas_prize')),
                ('product_as_prize', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.sponsoredproductforprize')),
                ('segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.segment')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPrizeDeliverOrderPaymntHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_amount', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payee_email', models.CharField(blank=True, max_length=255, null=True)),
                ('payee_marchnt_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payee_address', models.CharField(blank=True, max_length=255, null=True)),
                ('payer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('payer_email', models.CharField(blank=True, max_length=255, null=True)),
                ('payer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payer_post_code', models.CharField(blank=True, max_length=255, null=True)),
                ('payer_country_code', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('order_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.productprizedeliverorder')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrizeCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed_for_delivery', models.BooleanField(blank=True, default=False, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.productlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicableRulesForWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicable_rules', models.TextField()),
                ('product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.sponsoredproductforprize')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
