# Generated by Django 3.2.11 on 2022-03-23 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0015_auto_20220323_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_segments', models.CharField(max_length=3)),
                ('no_of_complt_spins', models.CharField(max_length=3)),
                ('spining_duration', models.CharField(max_length=3)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PointAs_Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_amount', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SegmentList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_no', models.IntegerField(default=0)),
                ('bg_color', models.CharField(max_length=255)),
                ('segment_prize_type', models.CharField(choices=[('1', 'Product'), ('2', 'Point')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SponsoredProductForPrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product_list')),
            ],
        ),
    ]
