# Generated by Django 3.2.11 on 2022-03-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesetting',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
