# Generated by Django 3.2.11 on 2022-03-25 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_segment'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmentlist',
            name='segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.segment'),
        ),
        migrations.AlterField(
            model_name='segmentlist',
            name='segment_no',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
