# Generated by Django 3.2.11 on 2022-03-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20220325_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmentlist',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='segmentlist',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
