# Generated by Django 3.2.11 on 2022-03-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20220325_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmentlist',
            name='prize_point_amount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
