# Generated by Django 3.2.11 on 2022-03-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_segmentlist_prize_point_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segmentlist',
            name='segment_no',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
