# Generated by Django 3.2.11 on 2022-03-27 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_alter_gamesetting_no_of_segments'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsoredproductforprize',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
