# Generated by Django 3.2.11 on 2022-04-08 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0058_alter_product_list_productimg'),
        ('game', '0010_sponsoredproductforprize_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsoredproductforprize',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productlist'),
        ),
    ]
