# Generated by Django 3.2.11 on 2022-05-05 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0073_auto_20220504_2104'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0011_alter_sponsoredproductforprize_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicableRulesForWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicable_rules', models.TextField()),
                ('product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productlist')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
