# Generated by Django 3.2.11 on 2022-05-05 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_applicablerulesforwinner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicablerulesforwinner',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.sponsoredproductforprize'),
        ),
    ]
