# Generated by Django 3.2.11 on 2022-05-07 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_alter_applicablerulesforwinner_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsoredproductforprize',
            name='prodct_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
