# Generated by Django 3.2.11 on 2022-05-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_sponsoredproductforprize_prodct_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmentlist',
            name='prize_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
