# Generated by Django 3.2.11 on 2022-05-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_segmentlist_prize_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalNumOfTimesPlayed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_times_played', models.IntegerField(default=0)),
            ],
        ),
    ]
