# Generated by Django 3.2.11 on 2022-05-21 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0081_alter_woocommerceproductlist_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0016_totalnumoftimesplayed'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrizeCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.productlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
