# Generated by Django 3.2.11 on 2022-05-21 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0081_alter_woocommerceproductlist_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0027_productdetailscheckboxcaptcha_product_id'),
        ('game', '0017_prizecart'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPrizeDeliverOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_total_amount', models.FloatField(blank=True, null=True)),
                ('total_amount', models.FloatField(blank=True, null=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('order_status', models.CharField(blank=True, choices=[('a', 'Approved'), ('p', 'Pending'), ('c', 'Cancel')], max_length=255, null=True)),
                ('delivery_status', models.BooleanField(blank=True, default=False, null=True)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('shipping_status', models.BooleanField(blank=True, default=False, null=True)),
                ('shipping_date', models.DateTimeField(blank=True, null=True)),
                ('order_note', models.TextField(blank=True, null=True)),
                ('payment_status', models.BooleanField(blank=True, default=False, null=True)),
                ('payment_options', models.CharField(blank=True, choices=[('cod', 'Cash on Delivery')], max_length=35, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('billing_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.billinginfo')),
                ('items', models.ManyToManyField(blank=True, to='product.OrderedItem')),
                ('shipping_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.shippinginfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
