# Generated by Django 3.2.11 on 2022-05-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_alter_productprizedeliverorder_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='prizecart',
            name='delivery_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
