# Generated by Django 3.2.11 on 2022-05-21 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_prizecart_delivery_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prizecart',
            old_name='delivery_status',
            new_name='confirmed_for_delivery',
        ),
    ]
