# Generated by Django 3.2.11 on 2022-05-22 01:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0081_alter_woocommerceproductlist_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0021_rename_delivery_status_prizecart_confirmed_for_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentDelivryRequestPrizeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('is_current', models.BooleanField(blank=True, default=False, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='productprizedeliverorder',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, to='game.CurrentDelivryRequestPrizeProduct'),
        ),
    ]
