# Generated by Django 3.2.11 on 2022-05-22 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0081_alter_woocommerceproductlist_options'),
        ('game', '0023_alter_productprizedeliverorder_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprizedeliverorder',
            name='items',
            field=models.ManyToManyField(blank=True, to='product.ProductList'),
        ),
    ]
