# Generated by Django 3.2.11 on 2022-05-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0025_alter_productprizedeliverorder_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameTermsPolicies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
