# Generated by Django 3.2.11 on 2022-06-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0026_gametermspolicies'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentdelivryrequestprizeproduct',
            name='shipping_cost',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='productprizedeliverorder',
            name='total_shipping_cost',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
