# Generated by Django 3.2.11 on 2022-06-22 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0028_productprizedeliverorderpaymnthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmentlist',
            name='product_cost',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
