# Generated by Django 3.2.11 on 2023-02-24 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0029_segmentlist_product_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmentlist',
            name='prize_type',
            field=models.CharField(blank=True, choices=[('random', 'Random'), ('periodic', 'Periodic')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='segmentlist',
            name='required_spin_to_win',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
