# Generated by Django 3.2.11 on 2022-06-01 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerDashboard', '0002_sellerpurchasedpackages'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerpurchasedpackages',
            name='paid_amount',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
