# Generated by Django 3.2.11 on 2022-02-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_verificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='status',
            field=models.CharField(blank=True, choices=[('verified', '1'), ('not_verified', '0')], max_length=20, null=True),
        ),
    ]
