# Generated by Django 3.2.11 on 2022-02-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_account_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'verified'), ('0', 'not_verified')], default=0, max_length=20, null=True),
        ),
    ]
