# Generated by Django 3.2.11 on 2022-02-26 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20220222_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationcode',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
