# Generated by Django 3.2.11 on 2022-02-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_verificationcode_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Verified'), ('0', 'Not Verified')], default=0, max_length=20, null=True),
        ),
    ]
