# Generated by Django 3.2.11 on 2022-02-27 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_account_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verificationcode',
            options={'ordering': ['-pk']},
        ),
    ]
