# Generated by Django 3.2.11 on 2022-03-02 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_verificationcode_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['-pk']},
        ),
    ]
