# Generated by Django 3.2.11 on 2022-04-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_billinginfo_shippinginfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinginfo',
            name='info_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shippinginfo',
            name='info_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
