# Generated by Django 3.2.11 on 2022-04-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20220403_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinginfo',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
