# Generated by Django 3.2.11 on 2022-04-05 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_billinginfo_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippinginfo',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
