# Generated by Django 3.2.11 on 2022-04-29 00:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_disclaimeragreedisagreeiplist'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMailInvitations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_to', models.CharField(blank=True, max_length=255)),
                ('msg', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
