# Generated by Django 3.2.11 on 2022-05-08 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_auto_20220508_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinginfo',
            name='default_billingAddress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.defaultbillinginfo'),
        ),
        migrations.AddField(
            model_name='shippinginfo',
            name='default_shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.defalutshippinginfo'),
        ),
    ]
