# Generated by Django 3.2.11 on 2022-05-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_buywinningchanceboxcaptcha_cartcheckboxcaptcha_categoryshopcheckboxcaptcha_checkoutcheckboxcaptcha_c'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetailscheckboxcaptcha',
            name='product_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
