# Generated by Django 3.2.11 on 2022-05-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_referalcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermailinvitations',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
