# Generated by Django 3.2.11 on 2022-05-31 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_usermailinvitations_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_agreed_withBetaTestTerms',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
